// Date: 11/3/2015 3:57:14 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.madmodding.space.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelPlayer;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSpaceSuit extends ModelPlayer {
	// fields
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer oxygen_Bag1;
	ModelRenderer oxygen_Bag;
	ModelRenderer head;
	ModelRenderer head12;
	ModelRenderer head11;
	ModelRenderer head10;
	ModelRenderer head9;
	ModelRenderer head8;
	ModelRenderer head7;
	ModelRenderer head6;
	ModelRenderer head5;
	ModelRenderer head4;
	ModelRenderer head3;
	ModelRenderer head2;
	ModelRenderer head1;

	public ModelSpaceSuit(float f, boolean addHelmet, boolean addChestPiece, boolean addLeggings, boolean addBoots) {
		super(f, true);
		textureWidth = 64;
		textureHeight = 64;

		body = new ModelRenderer(this, 16, 16);
		body.addBox(-4F, 0F, -2F, 8, 12, 4, f + 0.02f);
		body.setRotationPoint(0F, 0F, 0F);
		body.setTextureSize(64, 64);
		body.mirror = true;
		setRotation(body, 0F, 0F, 0F);
		rightarm = new ModelRenderer(this, 40, 16);
		rightarm.addBox(-3F, -2F, -2F, 4, 12, 4, f);
		rightarm.setRotationPoint(0F, 0F, 0F);
		rightarm.setTextureSize(64, 64);
		rightarm.mirror = true;
		setRotation(rightarm, 0F, 0F, 0F);
		leftarm = new ModelRenderer(this, 40, 16);
		leftarm.addBox(-1F, -2F, -2F, 4, 12, 4, f);
		leftarm.setRotationPoint(0F, 0F, 0F);
		leftarm.setTextureSize(64, 64);
		leftarm.mirror = true;
		setRotation(leftarm, 0F, 0F, 0F);
		rightleg = new ModelRenderer(this, 0, 16);
		rightleg.addBox(-2F, 0F, -2F, 4, 12, 4, f);
		rightleg.setRotationPoint(0F, 0F, 0F);
		rightleg.setTextureSize(64, 64);
		rightleg.mirror = true;
		setRotation(rightleg, 0F, 0F, 0F);
		leftleg = new ModelRenderer(this, 0, 35);
		leftleg.addBox(-2F, 0F, -2F, 4, 12, 4, f);
		leftleg.setRotationPoint(0F, 0F, 0F);
		leftleg.setTextureSize(64, 64);
		leftleg.mirror = true;
		setRotation(leftleg, 0F, 0F, 0F);
		oxygen_Bag1 = new ModelRenderer(this, 36, 40);
		oxygen_Bag1.addBox(-4F, 0F, -2F, 4, 4, 1, f);
		oxygen_Bag1.setRotationPoint(2F, 2F, 8.5F);
		oxygen_Bag1.setTextureSize(64, 64);
		oxygen_Bag1.mirror = true;
		setRotation(oxygen_Bag1, 0F, 0F, 0F);
		oxygen_Bag = new ModelRenderer(this, 36, 46);
		oxygen_Bag.addBox(-4F, 0F, -2F, 8, 12, 5, f);
		oxygen_Bag.setRotationPoint(0F, 0F, 4F);
		oxygen_Bag.setTextureSize(64, 64);
		oxygen_Bag.mirror = true;
		setRotation(oxygen_Bag, 0F, 0F, 0F);
		head = new ModelRenderer(this, 0, 0);
		head.addBox(-4F, -8F, -4F, 8, 8, 6, f + 0.01f);
		head.setRotationPoint(0F, 0F, 1F);
		head.setTextureSize(64, 64);
		head.mirror = true;
		setRotation(head, 0F, 0F, 0F);
		head12 = new ModelRenderer(this, 17, 45);
		head12.addBox(0F, 0F, 0F, 2, 3, 1, f);
		head12.setRotationPoint(-4F, 10F, -3F);
		head12.setTextureSize(64, 64);
		head12.mirror = true;
		setRotation(head12, 0F, 0F, 0F);
		head11 = new ModelRenderer(this, 17, 45);
		head11.addBox(0F, 0F, 0F, 2, 3, 1, f);
		head11.setRotationPoint(2F, 10F, -3F);
		head11.setTextureSize(64, 64);
		head11.mirror = true;
		setRotation(head11, 0F, 0F, 0F);
		head10 = new ModelRenderer(this, 17, 40);
		head10.addBox(-2F, 0F, 0F, 2, 3, 1, f);
		head10.setRotationPoint(2F, 6F, -3F);
		head10.setTextureSize(64, 64);
		head10.mirror = true;
		setRotation(head10, 0F, 0F, -0.5F);
		head9 = new ModelRenderer(this, 17, 40);
		head9.addBox(0F, 0F, 0F, 2, 3, 1, f);
		head9.setRotationPoint(-2F, 6F, -3F);
		head9.setTextureSize(64, 64);
		head9.mirror = true;
		setRotation(head9, 0F, 0F, 0.5F);
		head8 = new ModelRenderer(this, 50, 33);
		head8.addBox(-2F, 0F, 0F, 2, 4, 0, f);
		head8.setRotationPoint(4.5F, 3F, -3.4F);
		head8.setTextureSize(64, 64);
		head8.mirror = true;
		setRotation(head8, 0F, 0F, 1F);
		head7 = new ModelRenderer(this, 42, 33);
		head7.addBox(0F, 0F, 0F, 2, 3, 1, f + 0.01f);
		head7.setRotationPoint(2.5F, 0F, -3.5F);
		head7.setTextureSize(64, 64);
		head7.mirror = true;
		setRotation(head7, 0F, 0F, 0F);
		head6 = new ModelRenderer(this, 32, 33);
		head6.addBox(0F, 0F, 0F, 3, 3, 1, f + 0.02f);
		head6.setRotationPoint(-1.5F, 3F, -3.5F);
		head6.setTextureSize(64, 64);
		head6.mirror = true;
		setRotation(head6, 0F, 0F, 0F);
		head5 = new ModelRenderer(this, 17, 33);
		head5.addBox(0F, 0F, 0F, 6, 5, 1, f);
		head5.setRotationPoint(-3F, 2F, -2.8F);
		head5.setTextureSize(64, 64);
		head5.mirror = true;
		setRotation(head5, 0F, 0F, 0F);
		head4 = new ModelRenderer(this, 55, 0);
		head4.addBox(0F, 0F, 0F, 1, 1, 3, f + 0.01f);
		head4.setRotationPoint(3.8F, -6F, -4F);
		head4.setTextureSize(64, 64);
		head4.mirror = true;
		setRotation(head4, 0F, 0F, -1F);
		head3 = new ModelRenderer(this, 30, 7);
		head3.addBox(0F, 0F, -2F, 8, 3, 2, f);
		head3.setRotationPoint(-4F, -3.4F, -3.9F);
		head3.setTextureSize(64, 64);
		head3.mirror = true;
		setRotation(head3, -5.46F, 0F, 0F);
		head2 = new ModelRenderer(this, 0, 55);
		head2.addBox(0F, 0F, 0F, 8, 5, 3, f - 0.01f);
		head2.setRotationPoint(-4F, -6.9F, -4.7F);
		head2.setTextureSize(64, 64);
		head2.mirror = true;
		setRotation(head2, -0.1F, 0F, 0F);
		head1 = new ModelRenderer(this, 30, 0);
		head1.addBox(0F, 0F, 0F, 8, 2, 3, f);
		head1.setRotationPoint(-4F, -8F, -3F);
		head1.setTextureSize(64, 64);
		head1.mirror = true;
		setRotation(head1, -1F, 0F, 0F);
		this.bipedHead.cubeList.clear();
		this.bipedHeadwear.cubeList.clear();
		// 8,6,5,10,9,7
		if (addHelmet) {
			this.bipedHead.addChild(this.head);
			this.bipedHead.addChild(this.head1);
			this.bipedHead.addChild(this.head2);
			this.bipedHead.addChild(this.head3);
			this.bipedHead.addChild(this.head4);
		}

		this.bipedBody.cubeList.clear();
		if (addChestPiece) {
			this.bipedBody.addChild(this.body);
			this.bipedBody.addChild(this.oxygen_Bag);
			this.bipedBody.addChild(this.oxygen_Bag1);
			this.bipedBody.addChild(this.head5);
			this.bipedBody.addChild(this.head6);
			this.bipedBody.addChild(this.head7);
			this.bipedBody.addChild(this.head8);
			this.bipedBody.addChild(this.head9);
			this.bipedBody.addChild(this.head10);
		}
		if (addLeggings) {
			this.bipedBody.addChild(this.head11);
			this.bipedBody.addChild(this.head12);
		}
		this.bipedRightArm.cubeList.clear();
		if (addChestPiece) {
			this.bipedRightArm.addChild(this.rightarm);
		}

		this.bipedLeftArm.cubeList.clear();
		if (addChestPiece) {
			this.bipedLeftArm.addChild(this.leftarm);
		}

		this.bipedLeftLeg.cubeList.clear();
		if (addBoots) {
			this.bipedLeftLeg.addChild(this.leftleg);
		}
		if (addLeggings) {
		}

		this.bipedRightLeg.cubeList.clear();
		if (addBoots) {
			this.bipedRightLeg.addChild(this.rightleg);
		}
		if (addLeggings) {
		}
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);

		this.bipedHead.render(f5);
		this.bipedBody.render(f5);
		this.bipedLeftArm.render(f5);
		this.bipedRightArm.render(f5);
		this.bipedLeftLeg.render(f5);
		this.bipedRightLeg.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
