// Date: 11/2/2015 4:57:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.madmodding.space.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelAcidContainer extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape18;
    ModelRenderer Shape14;
    ModelRenderer Shape12;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape13;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape21;
    ModelRenderer Shape22;
    ModelRenderer Shape23;
    ModelRenderer Shape24;
    ModelRenderer Shape25;
    ModelRenderer Shape26;
    ModelRenderer Shape27;
    ModelRenderer Shape28;
    ModelRenderer Shape29;
    ModelRenderer Shape30;
    ModelRenderer Shape31;
  
  public ModelAcidContainer()
  {
    textureWidth = 512;
    textureHeight = 256;
    
      Shape1 = new ModelRenderer(this, 0, 50);
      Shape1.addBox(0F, 0F, 0F, 32, 8, 8);
      Shape1.setRotationPoint(-8F, -40F, -8F);
      Shape1.setTextureSize(512, 256);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 85, 0);
      Shape2.addBox(0F, 0F, 0F, 16, 8, 8);
      Shape2.setRotationPoint(24F, -40F, -8F);
      Shape2.setTextureSize(512, 256);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, -1F, 0F);
      Shape3 = new ModelRenderer(this, 140, 0);
      Shape3.addBox(0F, 0F, 0F, 8, 8, 16);
      Shape3.setRotationPoint(-8F, -40F, -8F);
      Shape3.setTextureSize(512, 256);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, -0.6F, 0F);
      Shape4 = new ModelRenderer(this, 0, 0);
      Shape4.addBox(0F, 0F, 0F, 8, 8, 32);
      Shape4.setRotationPoint(24.6F, -40F, 5.3F);
      Shape4.setTextureSize(512, 256);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 0);
      Shape5.addBox(0F, 0F, 0F, 8, 8, 32);
      Shape5.setRotationPoint(-17F, -40F, 5.3F);
      Shape5.setTextureSize(512, 256);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 140, 0);
      Shape6.addBox(0F, 0F, 0F, 8, 8, 16);
      Shape6.setRotationPoint(25.9F, -40F, 32.8F);
      Shape6.setTextureSize(512, 256);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, -0.579F, 0F);
      Shape7 = new ModelRenderer(this, 0, 50);
      Shape7.addBox(-32F, 0F, 0F, 32, 8, 8);
      Shape7.setRotationPoint(23.8F, -40F, 42.6F);
      Shape7.setTextureSize(512, 256);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 85, 0);
      Shape8.addBox(0F, 0F, 0F, 16, 8, 8);
      Shape8.setRotationPoint(-10.3F, -40F, 33F);
      Shape8.setTextureSize(512, 256);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, -0.99F, 0F);
      Shape9 = new ModelRenderer(this, 0, 80);
      Shape9.addBox(0F, 0F, -32F, 34, 2, 43);
      Shape9.setRotationPoint(-9F, -40F, 32F);
      Shape9.setTextureSize(512, 256);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 0, 80);
      Shape18.addBox(0F, 0F, -32F, 34, 2, 43);
      Shape18.setRotationPoint(-9F, 22F, 32F);
      Shape18.setTextureSize(512, 256);
      Shape18.mirror = true;
      setRotation(Shape18, 0F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 0, 0);
      Shape14.addBox(0F, 0F, 0F, 8, 8, 32);
      Shape14.setRotationPoint(-17F, 16F, 5.3F);
      Shape14.setTextureSize(512, 256);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 140, 0);
      Shape12.addBox(0F, 0F, 0F, 8, 8, 16);
      Shape12.setRotationPoint(-8F, 16F, -8F);
      Shape12.setTextureSize(512, 256);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, -0.6F, 0F);
      Shape10 = new ModelRenderer(this, 0, 50);
      Shape10.addBox(0F, 0F, 0F, 32, 8, 8);
      Shape10.setRotationPoint(-8F, 16F, -8F);
      Shape10.setTextureSize(512, 256);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape11 = new ModelRenderer(this, 85, 0);
      Shape11.addBox(0F, 0F, 0F, 16, 8, 8);
      Shape11.setRotationPoint(24F, 16F, -8F);
      Shape11.setTextureSize(512, 256);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, -1F, 0F);
      Shape13 = new ModelRenderer(this, 0, 0);
      Shape13.addBox(0F, 0F, 0F, 8, 8, 32);
      Shape13.setRotationPoint(24.6F, 16F, 5.3F);
      Shape13.setTextureSize(512, 256);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 140, 0);
      Shape15.addBox(0F, 0F, 0F, 8, 8, 16);
      Shape15.setRotationPoint(25.9F, 16F, 32.8F);
      Shape15.setTextureSize(512, 256);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, -0.579F, 0F);
      Shape16 = new ModelRenderer(this, 0, 50);
      Shape16.addBox(-32F, 0F, 0F, 32, 8, 8);
      Shape16.setRotationPoint(23.8F, 16F, 42.6F);
      Shape16.setTextureSize(512, 256);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 85, 0);
      Shape17.addBox(0F, 0F, 0F, 16, 8, 8);
      Shape17.setRotationPoint(-10.3F, 16F, 33F);
      Shape17.setTextureSize(512, 256);
      Shape17.mirror = true;
      setRotation(Shape17, 0F, -0.99F, 0F);
      Shape19 = new ModelRenderer(this, 0, 140);
      Shape19.addBox(0F, 0F, -32F, 34, 48, 43);
      Shape19.setRotationPoint(-9F, -32F, 32F);
      Shape19.setTextureSize(512, 256);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 220, 0);
      Shape20.addBox(0F, 0F, 0F, 2, 2, 43);
      Shape20.setRotationPoint(-8F, -45F, 0F);
      Shape20.setTextureSize(512, 256);
      Shape20.mirror = true;
      setRotation(Shape20, 0F, 0F, 0F);
      Shape21 = new ModelRenderer(this, 220, 0);
      Shape21.addBox(0F, 0F, 0F, 2, 2, 43);
      Shape21.setRotationPoint(8F, -45F, 0F);
      Shape21.setTextureSize(512, 256);
      Shape21.mirror = true;
      setRotation(Shape21, 0F, 0F, 0F);
      Shape22 = new ModelRenderer(this, 220, 0);
      Shape22.addBox(31F, 0F, 0F, 2, 2, 43);
      Shape22.setRotationPoint(-8F, -45F, 0F);
      Shape22.setTextureSize(512, 256);
      Shape22.mirror = true;
      setRotation(Shape22, 0F, 0F, 0F);
      Shape23 = new ModelRenderer(this, 200, 200);
      Shape23.addBox(0F, 0F, 0F, 0, 3, 43);
      Shape23.setRotationPoint(-7F, -43F, 0F);
      Shape23.setTextureSize(512, 256);
      Shape23.mirror = true;
      setRotation(Shape23, 0F, 0F, 0F);
      Shape24 = new ModelRenderer(this, 200, 200);
      Shape24.addBox(0F, 0F, 0F, 0, 3, 43);
      Shape24.setRotationPoint(9F, -43F, 0F);
      Shape24.setTextureSize(512, 256);
      Shape24.mirror = true;
      setRotation(Shape24, 0F, 0F, 0F);
      Shape25 = new ModelRenderer(this, 200, 200);
      Shape25.addBox(0F, 0F, 0F, 0, 3, 43);
      Shape25.setRotationPoint(24F, -43F, 0F);
      Shape25.setTextureSize(512, 256);
      Shape25.mirror = true;
      setRotation(Shape25, 0F, 0F, 0F);
      Shape26 = new ModelRenderer(this, 195, 0);
      Shape26.addBox(0F, 0F, -6F, 2, 2, 6);
      Shape26.setRotationPoint(8F, -45F, 0F);
      Shape26.setTextureSize(512, 256);
      Shape26.mirror = true;
      setRotation(Shape26, 1F, 0F, 0F);
      Shape27 = new ModelRenderer(this, 195, 0);
      Shape27.addBox(0F, 0F, -6F, 2, 2, 6);
      Shape27.setRotationPoint(-8F, -45F, 0F);
      Shape27.setTextureSize(512, 256);
      Shape27.mirror = true;
      setRotation(Shape27, 1F, 0F, 0F);
      Shape28 = new ModelRenderer(this, 195, 0);
      Shape28.addBox(0F, 0F, -6F, 2, 2, 6);
      Shape28.setRotationPoint(23F, -45F, 0F);
      Shape28.setTextureSize(512, 256);
      Shape28.mirror = true;
      setRotation(Shape28, 1F, 0F, 0F);
      Shape29 = new ModelRenderer(this, 195, 0);
      Shape29.addBox(0F, 0F, 0F, 2, 2, 6);
      Shape29.setRotationPoint(-8F, -45F, 43F);
      Shape29.setTextureSize(512, 256);
      Shape29.mirror = true;
      setRotation(Shape29, -1F, 0F, 0F);
      Shape30 = new ModelRenderer(this, 195, 0);
      Shape30.addBox(0F, 0F, 0F, 2, 2, 6);
      Shape30.setRotationPoint(8F, -45F, 43F);
      Shape30.setTextureSize(512, 256);
      Shape30.mirror = true;
      setRotation(Shape30, -1F, 0F, 0F);
      Shape31 = new ModelRenderer(this, 195, 0);
      Shape31.addBox(0F, 0F, 0F, 2, 2, 6);
      Shape31.setRotationPoint(23F, -45F, 43F);
      Shape31.setTextureSize(512, 256);
      Shape31.mirror = true;
      setRotation(Shape31, -1F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
    Shape9.render(f5);
    Shape18.render(f5);
    Shape14.render(f5);
    Shape12.render(f5);
    Shape10.render(f5);
    Shape11.render(f5);
    Shape13.render(f5);
    Shape15.render(f5);
    Shape16.render(f5);
    Shape17.render(f5);
    Shape19.render(f5);
    Shape20.render(f5);
    Shape21.render(f5);
    Shape22.render(f5);
    Shape23.render(f5);
    Shape24.render(f5);
    Shape25.render(f5);
    Shape26.render(f5);
    Shape27.render(f5);
    Shape28.render(f5);
    Shape29.render(f5);
    Shape30.render(f5);
    Shape31.render(f5);
  }
  public void renderModel(float f5)
  {
	  Shape1.render(f5);
	    Shape2.render(f5);
	    Shape3.render(f5);
	    Shape4.render(f5);
	    Shape5.render(f5);
	    Shape6.render(f5);
	    Shape7.render(f5);
	    Shape8.render(f5);
	    Shape9.render(f5);
	    Shape18.render(f5);
	    Shape14.render(f5);
	    Shape12.render(f5);
	    Shape10.render(f5);
	    Shape11.render(f5);
	    Shape13.render(f5);
	    Shape15.render(f5);
	    Shape16.render(f5);
	    Shape17.render(f5);
	    Shape19.render(f5);
	    Shape20.render(f5);
	    Shape21.render(f5);
	    Shape22.render(f5);
	    Shape23.render(f5);
	    Shape24.render(f5);
	    Shape25.render(f5);
	    Shape26.render(f5);
	    Shape27.render(f5);
	    Shape28.render(f5);
	    Shape29.render(f5);
	    Shape30.render(f5);
	    Shape31.render(f5);
  }
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
