// Date: 11/16/2015 5:58:08 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.madmodding.space.items.element;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class MadArmor extends ModelBiped {
	// fields
	ModelRenderer body;
	ModelRenderer rightarm;
	ModelRenderer leftarm;
	ModelRenderer rightleg;
	ModelRenderer leftleg;
	ModelRenderer helmet15;
	ModelRenderer helmet14;
	ModelRenderer helmet13;
	ModelRenderer helmet12;
	ModelRenderer helmet11;
	ModelRenderer helmet10;
	ModelRenderer helmet9;
	ModelRenderer helmet8;
	ModelRenderer helmet7;
	ModelRenderer helmet6;
	ModelRenderer helmet5;
	ModelRenderer helmet4;
	ModelRenderer helmet3;
	ModelRenderer helmet2;
	ModelRenderer helmet1;

	public MadArmor(float f, boolean addHelmet, boolean addChestPiece, boolean addLeggings, boolean addBoots) {
		{
			textureWidth = 64;
			textureHeight = 64;

			body = new ModelRenderer(this, 16, 16);
			body.addBox(-4F, 0F, -2F, 8, 12, 5, (float) (f+0.01));
			body.setRotationPoint(0F, 0F, -0.5F);
			body.setTextureSize(64, 64);
			body.mirror = true;
			setRotation(body, 0F, 0F, 0F);
			rightarm = new ModelRenderer(this, 42, 16);
			rightarm.addBox(-3F, -2F, -2F, 4, 6, 4, (float) (f+0.01));
			rightarm.setRotationPoint(0F, 0F, 0F);//rightarm.setRotationPoint(-5F, 2F, 0F);
			rightarm.setTextureSize(64, 64);
			rightarm.mirror = true;
			setRotation(rightarm, 0F, 0F, 0F);
			leftarm = new ModelRenderer(this, 42, 16);
			leftarm.addBox(-1F, -2F, -2F, 4, 6, 4, (float) (f+0.01));
			leftarm.setRotationPoint(0F, 0F, 0F);//leftarm.setRotationPoint(5F, 2F, 0F);
			leftarm.setTextureSize(64, 64);
			leftarm.mirror = true;
			setRotation(leftarm, 0F, 0F, 0F);
			rightleg = new ModelRenderer(this, 0, 16);
			rightleg.addBox(-2F, 0F, -2F, 4, 12, 4, (float) (f+0.01));
			rightleg.setRotationPoint(0F, 0F, 0F);//rightleg.setRotationPoint(-2F, 12F, 0F);
			rightleg.setTextureSize(64, 64);
			rightleg.mirror = true;
			setRotation(rightleg, 0F, 0F, 0F);
			leftleg = new ModelRenderer(this, 0, 16);
			leftleg.addBox(-2F, 0F, -2F, 4, 12, 4, (float) (f+0.01));
			leftleg.setRotationPoint(2F, 12F, 0F);
			leftleg.setRotationPoint(0F, 0F, 0F);//leftleg.setTextureSize(64, 64);
			leftleg.mirror = true;
			setRotation(leftleg, 0F, 0F, 0F);
			helmet15 = new ModelRenderer(this, 0, 0);
			helmet15.addBox(0F, 0F, 0F, 2, 4, 1, f-1);
			helmet15.setRotationPoint(1.6F, -4F, -5.5F);
			helmet15.setTextureSize(64, 64);
			helmet15.mirror = true;
			setRotation(helmet15, 0F, 0F, 0F);
			helmet14 = new ModelRenderer(this, 52, 0);
			helmet14.addBox(0F, 0F, 0F, 3, 4, 1, f-1);
			helmet14.setRotationPoint(-2.8F, -3.9F, -5.4F);
			helmet14.setTextureSize(64, 64);
			helmet14.mirror = true;
			setRotation(helmet14, 0F, 0F, -0.1F);
			helmet13 = new ModelRenderer(this, 52, 0);
			helmet13.addBox(-2.5F, 0F, 0F, 2, 4, 1, f-1);
			helmet13.setRotationPoint(2.6F, -4F, -5.5F);
			helmet13.setTextureSize(64, 64);
			helmet13.mirror = true;
			setRotation(helmet13, 0F, 0F, 0.1F);
			helmet12 = new ModelRenderer(this, 0, 0);
			helmet12.addBox(0F, 0F, 0F, 2, 4, 1, f-1);
			helmet12.setRotationPoint(-3.6F, -4F, -5.4F);
			helmet12.setTextureSize(64, 64);
			helmet12.mirror = true;
			setRotation(helmet12, 0F, 0F, 0F);
			helmet11 = new ModelRenderer(this, 42, 0);
			helmet11.addBox(-3F, 0F, 0F, 3, 2, 1, f-1);
			helmet11.setRotationPoint(4F, -8F, -5.5F);
			helmet11.setTextureSize(64, 64);
			helmet11.mirror = true;
			setRotation(helmet11, 0F, 0F, 0.2F);
			helmet10 = new ModelRenderer(this, 42, 0);
			helmet10.addBox(0F, 0F, 0F, 3, 2, 1, f-1);
			helmet10.setRotationPoint(-4F, -8F, -5.5F);
			helmet10.setTextureSize(64, 64);
			helmet10.mirror = true;
			setRotation(helmet10, 0F, 0F, -0.2F);
			helmet9 = new ModelRenderer(this, 13, 6);
			helmet9.addBox(0F, 0F, 0F, 2, 1, 0, f-1);
			helmet9.setRotationPoint(-1F, -5.5F, -5F);
			helmet9.setTextureSize(64, 64);
			helmet9.mirror = true;
			setRotation(helmet9, -0.1F, 0F, 0F);
			helmet8 = new ModelRenderer(this, 12, 0);
			helmet8.addBox(0F, 0F, 0F, 2, 4, 1, f-1);
			helmet8.setRotationPoint(-1F, -9.5F, -5F);
			helmet8.setTextureSize(64, 64);
			helmet8.mirror = true;
			setRotation(helmet8, -0.1F, 0F, 0F);
			helmet7 = new ModelRenderer(this, 42, 4);
			helmet7.addBox(0F, 0F, -2F, 1, 8, 2, f-1);
			helmet7.setRotationPoint(4.3F, -8F, -3.3F);
			helmet7.setTextureSize(64, 64);
			helmet7.mirror = true;
			setRotation(helmet7, 0F, 0.8F, 0F);
			helmet6 = new ModelRenderer(this, 42, 4);
			helmet6.addBox(0F, 0F, -2F, 1, 8, 2, f-1);
			helmet6.setRotationPoint(-5F, -8F, -4F);
			helmet6.setTextureSize(64, 64);
			helmet6.mirror = true;
			setRotation(helmet6, 0F, -0.8F, 0F);
			helmet5 = new ModelRenderer(this, 0, 45);
			helmet5.addBox(0F, 0F, 0F, 2, 1, 9, f-1);
			helmet5.setRotationPoint(-1F, -9.5F, -5F);
			helmet5.setTextureSize(64, 64);
			helmet5.mirror = true;
			setRotation(helmet5, -0.05F, 0F, 0F);
			helmet4 = new ModelRenderer(this, 0, 34);
			helmet4.addBox(0F, 0F, 0F, 8, 1, 9, f-1);
			helmet4.setRotationPoint(-4F, -9F, -5F);
			helmet4.setTextureSize(64, 64);
			helmet4.mirror = true;
			setRotation(helmet4, 0F, 0F, 0F);
			helmet3 = new ModelRenderer(this, 19, 0);
			helmet3.addBox(0F, 0F, 0F, 10, 8, 1, f-1);
			helmet3.setRotationPoint(-5F, -8F, 4F);
			helmet3.setTextureSize(64, 64);
			helmet3.mirror = true;
			setRotation(helmet3, 0F, 0F, 0F);
			helmet2 = new ModelRenderer(this, 0, 0-1);
			helmet2.addBox(0F, 0F, 0F, 1, 8, 8, f-1);
			helmet2.setRotationPoint(4F, -8F, -4F);
			helmet2.setTextureSize(64, 64);
			helmet2.mirror = true;
			setRotation(helmet2, 0F, 0F, 0F);
			helmet1 = new ModelRenderer(this, 0, 0);
			helmet1.addBox(0F, 0F, 0F, 1, 8, 8, f-1);
			helmet1.setRotationPoint(-5F, -8F, -4F);
			helmet1.setTextureSize(64, 64);
			helmet1.mirror = true;
			setRotation(helmet1, 0F, 0F, 0F);
			this.bipedHead.cubeList.clear();
			this.bipedHeadwear.cubeList.clear();
			// 8,6,5,10,9,7
			if (addHelmet) {
				this.bipedHead.addChild(this.helmet1);
				this.bipedHead.addChild(this.helmet2);
				this.bipedHead.addChild(this.helmet3);
				this.bipedHead.addChild(this.helmet4);
				this.bipedHead.addChild(this.helmet5);
				this.bipedHead.addChild(this.helmet6);
				this.bipedHead.addChild(this.helmet7);
				this.bipedHead.addChild(this.helmet8);
				this.bipedHead.addChild(this.helmet9);
				this.bipedHead.addChild(this.helmet10);
				this.bipedHead.addChild(this.helmet11);
				this.bipedHead.addChild(this.helmet12);
				this.bipedHead.addChild(this.helmet13);
				this.bipedHead.addChild(this.helmet14);
				this.bipedHead.addChild(this.helmet15);
			}

			this.bipedBody.cubeList.clear();
			if (addChestPiece) {
				this.bipedBody.addChild(this.body);
			}
			this.bipedRightArm.cubeList.clear();
			if (addChestPiece) {
				this.bipedRightArm.addChild(this.rightarm);
			}

			this.bipedLeftArm.cubeList.clear();
			if (addChestPiece) {
				this.bipedLeftArm.addChild(this.leftarm);
			}

			this.bipedLeftLeg.cubeList.clear();
			if (addBoots) {
				this.bipedLeftLeg.addChild(this.leftleg);
			}

			this.bipedRightLeg.cubeList.clear();
			if (addBoots) {
				this.bipedRightLeg.addChild(this.rightleg);
			}
		}
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);

		this.bipedHead.render(f5);
		this.bipedBody.render(f5);
		this.bipedLeftArm.render(f5);
		this.bipedRightArm.render(f5);
		this.bipedLeftLeg.render(f5);
		this.bipedRightLeg.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
