// Date: 04/12/2015 21:38:07
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.madmodding.space.blocks.tile.forge;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelForge extends ModelBase {
	// fields
	ModelRenderer F1;
	ModelRenderer F2;
	ModelRenderer F3;
	ModelRenderer F4;
	ModelRenderer F5;
	ModelRenderer F6;
	ModelRenderer F7;
	ModelRenderer F8;
	ModelRenderer F9;
	ModelRenderer F10;
	ModelRenderer F11;
	ModelRenderer F12;
	ModelRenderer F13;
	ModelRenderer F14;

	public ModelForge() {
		textureWidth = 64;
		textureHeight = 128;

		F1 = new ModelRenderer(this, 0, 0);
		F1.addBox(0F, 0F, 0F, 14, 16, 14);
		F1.setRotationPoint(-7F, 8F, -7F);
		F1.setTextureSize(64, 128);
		F1.mirror = true;
		setRotation(F1, 0F, 0F, 0F);
		F2 = new ModelRenderer(this, 0, 32);
		F2.addBox(0F, 0F, 0F, 11, 1, 1);
		F2.setRotationPoint(-5.5F, 7.4F, -5.5F);
		F2.setTextureSize(64, 128);
		F2.mirror = true;
		setRotation(F2, 0F, 0F, 0F);
		F3 = new ModelRenderer(this, 0, 32);
		F3.addBox(0F, 0F, 0F, 11, 1, 1);
		F3.setRotationPoint(-5.5F, 7.4F, 4.5F);
		F3.setTextureSize(64, 128);
		F3.mirror = true;
		setRotation(F3, 0F, 0F, 0F);
		F4 = new ModelRenderer(this, 0, 36);
		F4.addBox(0F, 0F, 0F, 1, 1, 9);
		F4.setRotationPoint(4.5F, 7.4F, -4.5F);
		F4.setTextureSize(64, 128);
		F4.mirror = true;
		setRotation(F4, 0F, 0F, 0F);
		F5 = new ModelRenderer(this, 0, 36);
		F5.addBox(0F, 0F, 0F, 1, 1, 9);
		F5.setRotationPoint(-5.5F, 7.4F, -4.5F);
		F5.setTextureSize(64, 128);
		F5.mirror = true;
		setRotation(F5, 0F, 0F, 0F);
		F6 = new ModelRenderer(this, 26, 32);
		F6.addBox(0F, 0F, 0F, 9, 1, 1);
		F6.setRotationPoint(-4.5F, 7.7F, -0.5F);
		F6.setTextureSize(64, 128);
		F6.mirror = true;
		setRotation(F6, 0F, 0F, 0F);
		F7 = new ModelRenderer(this, 26, 36);
		F7.addBox(0F, 0F, 0F, 1, 1, 9);
		F7.setRotationPoint(-0.5F, 7.7F, -4.5F);
		F7.setTextureSize(64, 128);
		F7.mirror = true;
		setRotation(F7, 0F, 0F, 0F);
		F8 = new ModelRenderer(this, 0, 47);
		F8.addBox(0F, 0F, 0F, 12, 12, 1);
		F8.setRotationPoint(-6F, 8.5F, 6.5F);
		F8.setTextureSize(64, 128);
		F8.mirror = true;
		setRotation(F8, 0F, 0F, 0F);
		F9 = new ModelRenderer(this, 29, 47);
		F9.addBox(0F, 0F, 0F, 12, 12, 1);
		F9.setRotationPoint(-6F, 8.5F, -7.5F);
		F9.setTextureSize(64, 128);
		F9.mirror = true;
		setRotation(F9, 0F, 0F, 0F);
		F10 = new ModelRenderer(this, 0, 64);
		F10.addBox(0F, 0F, 0F, 1, 12, 12);
		F10.setRotationPoint(6.5F, 8.5F, -6F);
		F10.setTextureSize(64, 128);
		F10.mirror = true;
		setRotation(F10, 0F, 0F, 0F);
		F11 = new ModelRenderer(this, 0, 64);
		F11.addBox(0F, 0F, 0F, 1, 12, 12);
		F11.setRotationPoint(-7.5F, 8.5F, -6F);
		F11.setTextureSize(64, 128);
		F11.mirror = true;
		setRotation(F11, 0F, 0F, 0F);
		F12 = new ModelRenderer(this, 0, 90);
		F12.addBox(0F, 0F, 0F, 16, 4, 16);
		F12.setRotationPoint(-8F, 20F, -8F);
		F12.setTextureSize(64, 128);
		F12.mirror = true;
		setRotation(F12, 0F, 0F, 0F);
		F13 = new ModelRenderer(this, 29, 61);
		F13.addBox(0F, 0F, 0F, 11, 10, 1);
		F13.setRotationPoint(-5.5F, 10.5F, -7.7F);
		F13.setTextureSize(64, 128);
		F13.mirror = true;
		setRotation(F13, 0F, 0F, 0F);
		F14 = new ModelRenderer(this, 30, 75);
		F14.addBox(0F, 0F, 0F, 8, 1, 1);
		F14.setRotationPoint(-4F, 12.5F, -8F);
		F14.setTextureSize(64, 128);
		F14.mirror = true;
		setRotation(F14, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		F1.render(f5);
		F2.render(f5);
		F3.render(f5);
		F4.render(f5);
		F5.render(f5);
		F6.render(f5);
		F7.render(f5);
		F8.render(f5);
		F9.render(f5);
		F10.render(f5);
		F11.render(f5);
		F12.render(f5);
		F13.render(f5);
		F14.render(f5);
	}

	public void renderModel(float f5) {
		F1.render(f5);
		F2.render(f5);
		F3.render(f5);
		F4.render(f5);
		F5.render(f5);
		F6.render(f5);
		F7.render(f5);
		F8.render(f5);
		F9.render(f5);
		F10.render(f5);
		F11.render(f5);
		F12.render(f5);
		F13.render(f5);
		F14.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
